nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:5173']
        allow_headers: ['content-type', 'authorization']
        expose_headers: []
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'PATCH', 'DELETE']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:5173']
            allow_headers: ['content-type', 'authorization']
            allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600