# config/security.yaml

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Users: 'auto'
        App\Entity\Doctors: 'auto'
        App\Entity\Secretary: 'auto'

    providers:
        users_in_memory: { memory: null }
        auth:
            entity:
                class: App\Entity\Users
                property: email
        doctor_auth:
            entity:
                class: App\Entity\Doctors
                property: lastname
        secretary_auth:
            entity:
                class: App\Entity\Secretary
                property: email
    firewalls:

        doctor:
            pattern: ^/api/auth
            provider: doctor_auth
            custom_authenticator: App\Security\DoctorAuthenticator
            stateless: false

        secretary:
            pattern: ^/api/auth
            provider: secretary_auth
            custom_authenticator: App\Security\SecretaryAuthenticator
            stateless: false

        main:
            lazy: true
            provider: auth
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true



    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/admin-dashboard, roles: ROLE_ADMIN }
        - { path: ^/api/auth/logindoctor, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/loginsecretary, roles: IS_AUTHENTICATED_ANONYMOUSLY }
