# config/services.yaml

parameters:
# Définir des paramètres globaux si nécessaire
# Exemple : pour définir des secrets, des chemins, etc.
# secret: '%env(APP_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            # Définit les arguments par défaut pour les services
            $authorizationChecker: '@security.authorization_checker'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Symfony\Component\Security\Core\Security:
        alias: 'security.helper'

    App\Security\DoctorUserProvider:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Security\DoctorAuthenticator:
        arguments:
            - '@security.user_password_hasher'
            - '@logger'
            - '@App\Security\DoctorUserProvider'
            - '@router'
        tags:
            - { name: 'security.authenticator' }


    App\Repository\DoctorsRepository:

    App\Context\DoctorApiContext:
        public: true

    App\Security\SecretaryUserProvider:
        arguments:
            - '@doctrine.orm.entity_manager'
            - public: true

    App\Security\SecretaryAuthenticator:
        arguments:
            - '@security.user_password_hasher'
            - '@logger'
            - '@App\Security\SecretaryUserProvider'
            - '@router'
            - '@security.csrf.token_manager'
        tags:
            - { name: 'security.authenticator' }

